[package]
authors = ["Jimmy Brisson <theotherjimmy@gmail.com>"]
name = "cmsis-cli"
version = "0.1.0"
edition = "2018"

[lib]
name = "cmsis_cli"
path = "src/lib.rs"

[[bin]]
name = "cmsis-cli"
path = "src/main.rs"

[dependencies]
app_dirs = "1.2.1"
clap = "2.19.0"
failure = "0.1.1"
slog = "^2"
slog-async = "^2"
slog-term = "^2"
pbr = "^1.0.0"

cmsis-pack = { version = "0.1.0", path = "../cmsis-pack" }