[package]
name = "cmsis-cffi"
version = "0.1.0"
authors = ["Jimmy Brisson <theotherjimmy@gmail.com>"]
edition = "2018"

[lib]
name = "cmsis_cffi"
crate-type = ["cdylib"]

[dependencies]
log = "0.4.8"
simplelog = "0.7.4"
failure = "0.1.1"
cmsis-pack = { version = "0.1.0", path = "../cmsis-pack" }

[build-dependencies]
cbindgen = "0.9.1"